<?php
/**
 * Implements hook_views_api().
 */
function dexp_testimonial_views_api() {
  return array("api" => "3.0");
}

/**
 * Implements hook_node_info().
 */
function dexp_testimonial_node_info() {
  $items = array(
    'testimonial' => array(
      'name' => t('Testimonial'),
      'base' => 'node_content',
      'description' => '',
      'has_title' => '1',
      'title_label' => t('Title'),
      'help' => '',
    ),
  );
  return $items;
}